### PR TITLE
Fix show_after error when sizeof fails to determine DataType size

### LINKED ISSUE #410: Handling abstract types?
Not sure if I'm creating false memories but I thought in the past I could create YAXArrays with mixed types?

```julia
test_x = stack(Vector{Union{Int,String}}[[1, "Test"], [2, "Test2"]])
YAXArray(test_x)
```

```julia
┌ Warning: Can not determine size of element type. Using DiskArrays.fallback_element_size[] = 100 bytes
└ @ DiskArrays C:\Users\tiwanaga\.julia\packages\DiskArrays\bZBJE\src\chunks.jl:305
╭──────────────────────────────────────╮
│ 2×2 YAXArray{Union{Int64, String},2} │
├──────────────────────────────────────┴──────────────────────── dims ┐
  ↓ Dim_1 Sampled{Int64} Base.OneTo(2) ForwardOrdered Regular Points,
  → Dim_2 Sampled{Int64} Base.OneTo(2) ForwardOrdered Regular Points
├─────────────────────────────────────────────────────────── metadata ┤
  Dict{String, Any}()
├────────────────────────────────────────────────────────── file size ┤
Error showing value of type YAXArrays.Cubes.YAXArray{Union{Int64, String}, 2, Matrix{Union{Int64, String}}, Tuple{DimensionalData.Dimensions.Dim{:Dim_1, DimensionalData.Dimensions.Lookups.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.Lookups.ForwardOrdered, DimensionalData.Dimensions.Lookups.Regular{Int64}, DimensionalData.Dimensions.Lookups.Points, DimensionalData.Dimensions.Lookups.NoMetadata}}, DimensionalData.Dimensions.Dim{:Dim_2, DimensionalData.Dimensions.Lookups.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.Lookups.ForwardOrdered, DimensionalData.Dimensions.Lookups.Regular{Int64}, DimensionalData.Dimensions.Lookups.Points, DimensionalData.Dimensions.Lookups.NoMetadata}}}, Dict{String, Any}}:
ERROR: Argument is an abstract type and does not have a definite size.
Stacktrace:
  [1] sizeof(x::Type)
    @ Base .\essentials.jl:631
  [2] cubesize(c::YAXArrays.Cubes.YAXArray{Union{Int64, String}, 2, Matrix{Union{…}}, Tuple{DimensionalData.Dimensions.Dim{…}, DimensionalData.Dimensions.Dim{…}}, Dict{String, Any}})
    @ YAXArrays.Cubes C:\Users\tiwanaga\.julia\packages\YAXArrays\zyFvF\src\Cubes\Cubes.jl:501
  [3] show_after(io::IOContext{Base.TTY}, mime::MIME{Symbol("text/plain")}, c::YAXArrays.Cubes.YAXArray{Union{Int64, String}, 2, Matrix{Union{…}}, Tuple{DimensionalData.Dimensions.Dim{…}, DimensionalData.Dimensions.Dim{…}}, Dict{String, Any}})
    @ YAXArrays.Cubes C:\Users\tiwanaga\.julia\packages\YAXArrays\zyFvF\src\Cubes\Cubes.jl:512
  [4] show(io::IOContext{Base.TTY}, mime::MIME{Symbol("text/plain")}, A::YAXArrays.Cubes.YAXArray{Union{Int64, String}, 2, Matrix{Union{…}}, Tuple{DimensionalData.Dimensions.Dim{…}, DimensionalData.Dimensions.Dim{…}}, Dict{String, Any}})
    @ DimensionalData C:\Users\tiwanaga\.julia\packages\DimensionalData\BoJag\src\array\show.jl:17
  [5] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
```

### PR DESCRIPTION
**Pull request by Zapiano**
This error is preventing users from creating YAXArrays of Strings} and Unions that contain Strings.

closes #410

### CODE REVIEW

File: src/Cubes/Cubes.jl [hunk 1]
```diff
@@ -510,7 +510,11 @@ function DD.show_after(io::IO, mime, c::YAXArray)
     blockwidth = get(io, :blockwidth, 0)
     DD.print_block_separator(io, "file size", blockwidth, blockwidth)
     println(io, " ")
-    println(io, "  file size: ", formatbytes(cubesize(c)))
+    try
+        println(io, "  file size: ", formatbytes(cubesize(c)))
+    catch e
+        e isa ErrorException ? println(" could not determine DataType size.") : rethrow(e)
```
Comment (felixcremer) [inline src/Cubes/Cubes.jl:516]: If we rethrow the error, we will get a better message but still can't show the cube without an error. So I think that this should not be rethrowing.

File: src/Cubes/Cubes.jl [hunk 2]
```diff
@@ -510,7 +510,11 @@ function DD.show_after(io::IO, mime, c::YAXArray)
     blockwidth = get(io, :blockwidth, 0)
     DD.print_block_separator(io, "file size", blockwidth, blockwidth)
     println(io, " ")
-    println(io, "  file size: ", formatbytes(cubesize(c)))
+    try
```
Comment (felixcremer) [inline src/Cubes/Cubes.jl:513]: I don't like the use of try catch in this.
Could we use Base.summarysize(first(c)) instead of sizeof(eltype(c))  in the definition of cubesize?
This should give the same result for plain types like Int and Float64 and gives an approximate size for other types like string.

Comment (felixcremer) [reply src/Cubes/Cubes.jl:513]: The problem is, that we would introduce a getindex call which might be even more problematic than the use of try catch. So I am fine with that or with removing this info and only enabling that for certain eltypes where we know that sizeof is giving the right answer.
We could do that by putting the lines 511 to 513 together into a print_cubesize function which can then dispatch to the eltype of the cube and which can default to nothing to not print this information.

**Review by felixcremer — CHANGES_REQUESTED** [review]
Thanks for trying to tackle this, but I think, that it would be good to not have a try catch in the show method.

File: src/Cubes/Cubes.jl (hunk 1 above)
Comment (lazarusA) [reply src/Cubes/Cubes.jl:516]: @felixcremer what's is blocking this?

File: src/Cubes/Cubes.jl (hunk 2 above)
Comment (Zapiano) [reply src/Cubes/Cubes.jl]: > The problem is, that we would introduce a getindex call which might be even more problematic than the use of try catch. So I am fine with that or with removing this info and only enabling that for certain eltypes where we know that sizeof is giving the right answer. We could do that by putting the lines 511 to 513 together into a print_cubesize function which can then dispatch to the eltype of the cube and which can default to nothing to not print this information.

Thanks for the response and sorry for the delay.

I made a change checking for some specific eltypes for which the function `sizeof` is known to behave well before printing the size of the datacube. Let me know if that approach is better or what you think I need to change.
